# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths:
    - 'cfile_folder/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      # Runs check file
      - name: file listing
        run: ls
            
      # Runs polyspace server
      - name: Run polyspace server
        run: polyspace-bug-finder-server -sources ./cfile_folder/ZeroDivision.c
        
      # Check current resulting file
      - name: show current location
        run: ls
      - name: move result (log file)
        run: Move-Item -Path ./***.log -Destination ./polyspace_result
        
        
